---
services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    hostname: readarr
    restart: unless-stopped
    network_mode: host
    volumes:
      - /home/eric/mediaconfigs/readarr:/config
      - /home/eric/mediadata:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_LosAngeles
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8787"]
      interval: 1m30s
      timeout: 10s
      retries: 3