# server.compose.yml
---
networks:
  default:
    external: true
    name: proxy-tsnet

configs:
  traefik.toml:
    file: configs/traefik/traefik.toml
  dynamic.toml:
    file: configs/traefik/dynamic.toml
  prometheus.yml:
    file: configs/prometheus/prometheus.yml
  rules.yml:
    file: configs/prometheus/rules.yml
  alertmanager.yml:
    file: configs/prometheus/alertmanager.yml
  settings.yaml:
    file: configs/homepage/settings.yaml
  docker.yaml:
   file: configs/homepage/docker.yaml
  bookmarks.yaml:
    file: configs/homepage/bookmarks.yaml
  services.yaml:
   file: configs/homepage/services.yaml
  widgets.yaml:
    file: configs/homepage/widgets.yaml
  
include:
  - path: compose/infra/traefik.compose.yml
  - path: compose/infra/whoami.compose.yml
  - path: compose/infra/mysql.compose.yml

  - path: compose/apps/homepage.compose.yml
  - path: compose/apps/gitea.compose.yml
  - path: compose/apps/homebox.compose.yml

  - path: compose/monitoring/cadvisor.compose.yml
  - path: compose/monitoring/prometheus.compose.yml
  - path: compose/monitoring/grafana.compose.yml