---
include:
  - path: traefik.compose.yml

volumes:
  gitea_data:
    external: true
  mysql_data:
    external: true
    
services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    environment: 
    - GITEA__database__DB_TYPE=mysql
    - GITEA__database__HOST=db:3306
    - GITEA__database__NAME=gitea
    - GITEA__database__USER=gitea
    - GITEA__database__PASSWD=gitea
    volumes:
      - gitea_data:/data
    expose:
      - 3000
      - 22
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.entrypoints=web"
      - "traefik.http.routers.gitea.rule=Host(`gitea.ecs.lan`)"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      - "traefik.tcp.routers.gitea.entrypoints=ssh"
      - "traefik.tcp.routers.gitea.rule=HostSNI(`*`)"
      - "traefik.tcp.services.gitea.loadbalancer.server.port=22"
    depends_on:
      traefik-srv:
        condition: service_healthy
      db:
        condition: service_healthy
      
  # !NOTE The currently deployed instance does not use this MySQL db,
  # it's using the SQLite db that's stored in the volume. This is
  # here for future reference.
  db:
    image: mysql:8
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=gitea
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=gitea
      - MYSQL_DATABASE=gitea
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
     interval: 10s
     timeout: 5s
     retries: 5