---
include:
  - path: traefik.compose.yml

volumes:
  homebox_data:
    external: true

services:
  homebox:
    image: ecshreve/homebox-dev:latest
    container_name: homebox
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    ports:
      - 7745
    volumes:
      - homebox_data:/data
    labels:
      - traefik.enable=true
      - homepage.group=apps
      - homepage.name=homebox
      - homepage.icon=homebox
      - homepage.href=http://homebox.ecs.lan
    depends_on:
      traefik-srv:
        condition: service_healthy
