---
include:
  - path: traefik.compose.yml

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    expose:
      - 3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: docker_conf
        target: /app/config/docker.yaml
      - source: bookmarks_conf
        target: /app/config/bookmarks.yaml
      - source: services_conf
        target: /app/config/services.yaml
      - source: widgets_conf
        target: /app/config/widgets.yaml
    labels:
      - traefik.enable=true
    depends_on:
      traefik:
        condition: service_healthy

configs:
  widgets_conf:
    content: |
      ---
      - resources:
          cpu: true
          memory: true
          disk: /
          uptime: true

  docker_conf:
    content: |
      ---
      my-docker:
        socket: /var/run/docker.sock
        
  bookmarks_conf:
    content: |
      ---
      - devlinks:
        - Github:
          - abbr: GH
            icon: github
            href: https://github.com/
        - Cloudflare:
          - abbr: CF
            icon: cloudflare
            href: https://cloudflare.com/
        - Digital Ocean:
          - abbr: DO
            icon: digital-ocean
            href: https://digitalocean.com/
        - Hugging Face:
          - abbr: HF
            icon: hugging-face
            href: https://huggingface.co/

  services_conf:
    content: |
      ---
      - apps:
        - coder:
            href: http://coder.ecs.lan
            icon: coder
            siteMonitor: http://coder.ecs.lan

      - infra:
        - unifi:
            href: http://${UNIFI_CONTROLLER_IP}
            icon: unifi
            siteMonitor: https://${UNIFI_CONTROLLER_IP}
            widget:
              type: unifi
              url: https://${UNIFI_CONTROLLER_IP}
              username: slab
              password: $UNIFI_PW
              fields: ["uptime", "lan_users", "wlan_users"]

        - pihole:
            href: http://vault:8088/admin
            icon: pi-hole
            server: my-docker
            container: Pi-Hole
            siteMonitor: http://vault:8088/admin
            widget:
              type: pihole
              url: http://vault:8088
              key: ${PIHOLE_KEY}
              fields: [queries, blocked, gravity]

        - traefik:
            href: http://traefik.ecs.lan
            icon: traefik-proxy
            server: my-docker
            container: traefik
            siteMonitor: http://traefik.ecs.lan:8081
            widget:
              type: traefik
              url: http://traefik-ts:8081