[[task]]
    id = "deployall"
    type = "short"
    description = "Deploy all services via compose"
    cmd = "docker-compose up -d"

[[task]]
    id = "codersvc"
    type = "long"
    description = "Run the coder server in the background"
    cmd = "coder server"