# whoami.compose.yml
---
services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - homepage.group=apps
      - homepage.name=whoami
      - homepage.icon=docker
      - homepage.href=http://whoami.ecs.lan
      - homepage.siteMonitor=http://whoami:80

  