# This was used when I was running the coder binary on my laptop and still
# wanted to use traefik in between.
#
# Currently I have coder running as a system service on a VM and listening
# on port 80, in addition to a DNS record on my router pointing coder.ecs.lan
# to the tailscale IP of that VM.
#
# [http]
#     [http.routers]
#         [http.routers.coder-rtr]
#             entryPoints = ["web"]
#             service = "coder-svc"
#             rule = "Host(`coder.ecs.lan`)"

# [http.services]
#     [http.services.coder-svc.loadBalancer]
#         [[http.services.coder-svc.loadBalancer.servers]]
#             url = "http://mbp:3001"

[http.middlewares]
    [http.middlewares.custcors.headers]
          accessControlAllowMethods = ["*"]
          accessControlAllowHeaders = ["*"]
          accessControlAllowOriginList = ["*"]
          accessControlMaxAge = 100
          addVaryHeader = true