[global]
    checkNewVersion = true
    sendAnonymousUsage = false
[metrics]
    [metrics.prometheus]
        addEntryPointsLabels = true
        addRoutersLabels = true
        addServicesLabels = true
[entryPoints]
    [entryPoints.web]
        address = ":80"
        asDefault = true
    [entryPoints.web.forwardedHeaders]
        insecure = true
    [entryPoints.web.proxyProtocol]
        insecure = true
    # [entryPoints.ssh]
    #     address = ":22"
    [entryPoints.traefik]
        address = ":8080"
[accessLog]
    filePath = "/log/access.log"
    format = "json"
    [accessLog.fields]
        defaultMode = "keep"
    [accessLog.fields.names]
        StartUTC = "drop"
[log]
    filePath = "/log/traefik.log"
    format = "json"
[api]
    insecure = true
[ping]
    entryPoint = "traefik"
[providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    defaultRule = "Host(`{{ .ContainerName }}.ecs.lan`)"
    exposedByDefault = false
[providers.file]
    filename = "/etc/traefik/dynamic.toml"