---
- infra:
  - unifi:
      href: "http://{{HOMEPAGE_VAR_UNIFI_CONTROLLER_IP}}"
      icon: unifi
      siteMonitor: "https://{{HOMEPAGE_VAR_UNIFI_CONTROLLER_IP}}"
      widget:
        type: unifi
        url: "https://{{HOMEPAGE_VAR_UNIFI_CONTROLLER_IP}}"
        username: "{{HOMEPAGE_VAR_UNIFI_LOCAL_USER}}"
        password: "{{HOMEPAGE_VAR_UNIFI_PW}}"
  - coder:
      href: "http://coder.ecs.lan"
      icon: coder
      siteMonitor: "http://coder.ecs.lan"
      widget:
        type: tailscale
        deviceid: "{{HOMEPAGE_VAR_TAILSCALE_DEVICE}}"
        key: "{{HOMEPAGE_VAR_TAILSCALE_KEY}}"

- apps:
  - gitea:
      href: "http://gitea.ecs.lan"
      icon: gitea
      container: gitea
      server: my-docker
      siteMonitor: "http://gitea.ecs.lan"
  - homebox:
      href: "http://homebox.ecs.lan"
      container: homebox
      icon: homebox
      server: my-docker
      siteMonitor: "http://homebox.ecs.lan"
  - homepage:
      href: "http://homepage.ecs.lan"
      icon: homepage
      container: homepage
      siteMonitor: "http://homepage.ecs.lan"
      server: my-docker

- monitoring:
  - traefik:
      href: http://traefik.ecs.lan:8080
      icon: traefik-proxy
      server: my-docker
      container: traefik
      siteMonitor: http://traefik.ecs.lan:8080
      widget:
        type: traefik
        url: http://traefik:8080
  - grafana:
      href: "http://grafana.ecs.lan"
      icon: grafana
      container: grafana
      server: my-docker
      siteMonitor: "http://grafana.ecs.lan"
      widget:
        type: grafana
        url: "http://grafana.ecs.lan"
        username: admin
        password: admin
  - prometheus:
      href: "http://prometheus.ecs.lan"
      icon: prometheus
      container: prometheus
      server: my-docker
      siteMonitor: "http://prometheus.ecs.lan"
      widget:
        type: prometheus
        url: "http://prometheus.ecs.lan"

- backend:
  - cadvisor:
      href: "http://cadvisor.ecs.lan"
      icon: cadvisor
      container: cadvisor
      server: my-docker
      siteMonitor: "http://cadvisor.ecs.lan"
  - promtail:
      href: "http://promtail.ecs.lan"
      icon: prometheus
      container: promtail
      server: my-docker

- logging:
  - loki:
      href: "http://grafana.ecs.lan/a/grafana-lokiexplore-app/explore"
      icon: loki
      container: loki
      server: my-docker
      siteMonitor: "http://loki.ecs.lan/ready"
      showStats: false
      widget:
        type: iframe
        name: myIframe
        src: http://grafana.ecs.lan/d/Ts25XhS4zawd/docker-logs?orgId=1&refresh=1m&var-host=All&var-service=All&var-query=&showCategory=Axis
        classes: h-72 sm:h-72 md:h-72 lg:h-96 xl:h-96 2xl:h-96 # optional, use tailwind height classes, see https://tailwindcss.com/docs/height
        referrerPolicy: same-origin # optional, no default
        allowPolicy: autoplay; fullscreen; gamepad # optional, no default
        loadingStrategy: eager # optional, default: eager

