--- 
- unifi_console:
    href: "http://{{HOMEPAGE_VAR_UNIFI_CONTROLLER_IP}}"
    url: "https://{{HOMEPAGE_VAR_UNIFI_CONTROLLER_IP}}"
    username: "{{HOMEPAGE_VAR_UNIFI_LOCAL_USER}}"
    password: "{{HOMEPAGE_VAR_UNIFI_PW}}"

- resources:
    cpu: true
    memory: true
    disk: /
    uptime: true

- search:
    provider: duckduckgo

- datetime:
    format:
      dateStyle: short
      timeStyle: short
      qhour12: true