# prometheus.yml
---
global:
  scrape_interval: 10s
  evaluation_interval: 10s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    metrics_path: /metrics

  # TODO: re-enable these scrapes
  # - job_name: "traefik"
  #   static_configs:
  #     - targets: ["traefik:8081"]
  #   metrics_path: /metrics

  # - job_name: "synology-node-exporter"
  #   static_configs:
  #     - targets: ["vault:9100"]
  #   metrics_path: /metrics

  # - job_name: "docker-daemon"
  #   static_configs:
  #     - targets: ["vault:9323"]
  #   metrics_path: /metrics

  # - job_name: "cadvisor"
  #   static_configs:
  #     - targets: ["cadvisor:8080"]
  #   metrics_path: /metrics
