# prometheus.yml
---
global:
  scrape_interval: 10s
  evaluation_interval: 10s
  scrape_timeout: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    metrics_path: /metrics

  - job_name: "traefik"
    static_configs:
      - targets: ["traefik.ecs.lan:8080"]
    metrics_path: /metrics

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "dockerhost"
    static_configs:
      - targets: ["node-exporter:9100", "cloudbox0:9100"]

  - job_name: "promtail"
    honor_timestamps: true
    static_configs:
      - targets: ["promtail:9080", "cloudbox0:9080"]
