# mysql.compose.yml
---
volumes:
  mysql_data:
    external: true
    
services:
  db:
    image: mysql:8
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      traefik:
        condition: service_started

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    expose:
      - 8080
    labels:
      - traefik.enable=true
    depends_on:
      db:
        condition: service_healthy

  
