# traefik.compose.yml
---
volumes:
  traefik_logs:
    external: true
    
services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    configs:
      - source: traefik.toml
        target: /etc/traefik/traefik.toml
      - source: dynamic.toml
        target: /etc/traefik/dynamic.toml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_logs:/log
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 5s
      retries: 5
     