# whoami.compose.yml
---
services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    hostname: whoami
    restart: unless-stopped
    expose:
      - 80
    labels:
      - traefik.enable=true
    depends_on:
      traefik:
        condition: service_healthy

  