# grafana.compose.yml
---
volumes:
  grafana_data:
    external: true
    
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
    configs:
      - source: datasource.yml
        target: /etc/grafana/provisioning/datasources/datasource.yml
    volumes:
      - grafana_data:/var/lib/grafana
    expose:
     - 3000
    labels:
      - traefik.enable=true
    depends_on:
      prometheus:
        condition: service_started
