# grafana.compose.yml
---
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    expose:
     - 3000
    labels:
      - traefik.enable=true
      - homepage.group=metrics
      - homepage.name=grafana
      - homepage.icon=grafana
      - homepage.href=http://grafana.ecs.lan
      - homepage.siteMonitor=http://grafana.ecs.lan
      - homepage.widget.type=grafana
      - homepage.widget.url=http://grafana.ecs.lan
      - homepage.widget.username=admin
      - homepage.widget.password=admin
