# jaeger.compose.yml
---
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
      - PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR=true

    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
      - "4317:4317"
      - "4318:4318"
    labels:
      - traefik.enable=true
      - traefik.http.routers.jaeger.rule=Host(`jaeger.ecs.lan`)
      - traefik.http.services.jaeger.loadbalancer.server.port=16686
    depends_on:
      - traefik