# prometheus.compose.yml
---
volumes:
  prometheus_data:
    external: true

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    configs:
      - source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
    volumes:
      - prometheus_data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway" # Needed for cAdvisor host
    expose:
      - 9090
    labels:
      - traefik.enable=true
    depends_on:
      traefik:
        condition: service_started
