# gitea.compose.yml
---
volumes:
  gitea_data:
    external: true

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    environment: 
      - GITEA__database__DB_TYPE=${DB_TYPE}
      - GITEA__database__HOST=${DB_HOST}
      - GITEA__database__NAME=${DB_NAME}
      - GITEA__database__USER=${DB_USER}
      - GITEA__database__PASSWD=${DB_PASS}
    volumes:
      - gitea_data:/data
    expose:
      - 3000
      - 22 #TODO work through ssh forwarding in new vm network configuration
    labels:
      - traefik.enable=true
      - traefik.http.routers.gitea.entrypoints=web
      - traefik.http.routers.gitea.rule=Host(`gitea.ecs.lan`)
      - traefik.http.services.gitea.loadbalancer.server.port=3000
    depends_on:
      traefik:
        condition: service_started
      db:
        condition: service_healthy
