# homepage.compose.yml
---
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
      - HOMEPAGE_VAR_UNIFI_LOCAL_USER=${HOMEPAGE_VAR_UNIFI_LOCAL_USER}
      - HOMEPAGE_VAR_UNIFI_PW=${HOMEPAGE_VAR_UNIFI_PW}
      - HOMEPAGE_VAR_UNIFI_CONTROLLER_IP=${HOMEPAGE_VAR_UNIFI_CONTROLLER_IP}
    expose:
      - 3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: docker.yaml
        target: /app/config/docker.yaml
      - source: bookmarks.yaml
        target: /app/config/bookmarks.yaml
      - source: services.yaml
        target: /app/config/services.yaml
      - source: widgets.yaml
        target: /app/config/widgets.yaml
      - source: settings.yaml
        target: /app/config/settings.yaml
    labels:
      - traefik.enable=true
    depends_on:
      traefik: 
        condition: service_started
