---
services:
  homebox:
    image: ecshreve/homebox-dev:latest
    container_name: homebox
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    ports:
      - 7745
    volumes:
      - homebox_data:/data
    labels:
      - traefik.enable=true
      - homepage.group=apps
      - homepage.name=homebox
      - homepage.icon=homebox
      - homepage.href=http://homebox.ecs.lan
      - homepage.siteMonitor=http://homebox.ecs.lan
      - homepage.showStats=true
      # - homepage.widget.type=homebox
      # - homepage.widget.url=http://homebox.ecs.lan
